
package GUI;
import civitas.CivitasJuego;
import civitas.OperacionesJuego;
import java.util.ArrayList;
import civitas.Jugador;
import civitas.SalidasCarcel;
import javax.swing.JOptionPane;

public class CivitasView extends javax.swing.JFrame {
    CivitasJuego juego;
    JugadorPanel jugadorPanel;
    GestionarDialog gestionarD = new GestionarDialog(this);
    
    public CivitasView() {
 
        initComponents();
        jugadorPanel = new JugadorPanel();
        contenedorVistaJugador.add(jugadorPanel);
        repaint();
        revalidate();
    }

    void setCivitasJuego(CivitasJuego juego) {
        this.juego=juego;
        this.actualizarVista();
        setVisible(true);
    }
    int getGestion() {
        return gestionarD.getGestion();
    }
    
    int getPropiedad() {
        return gestionarD.getPropiedad();
    }
    
    void actualizarVista(){
        jugadorPanel.setJugador(juego.getJugadorActual());
        TextoCasilla.setText(juego.getCasillaActual().toString()); 
        Ranking.setVisible(false);
        TextoRanking.setVisible(false);
        
        if(juego.finalDelJuego()) {
            String lista2="";
            ArrayList <Jugador> lista =juego.ranking();
            for(int i=0;i<lista.size();i++) {
               lista2=lista2+lista.get(i).getNombre()+"\n";
            }
            TextoRanking.setText(lista2);
            Ranking.setVisible(true);
            TextoRanking.setVisible(true);
        }
        pack();
        repaint();
        revalidate();
    }
    
    SalidasCarcel salirCarcel() {
        String[] opciones = {"SALIR PAGANDO", "SALIR TIRANDO"};
        int respuesta = JOptionPane.showOptionDialog(null, "¿Cómo quieres salir de la cárcel?", "Salir de la cárcel", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
        
        if(respuesta==0) {
            return SalidasCarcel.PAGANDO;
        }else{
            return SalidasCarcel.TIRANDO;
        }
    }
    
    void gestionar() {
        gestionarD.gestionar(juego.getJugadorActual());
        gestionarD.pack();
        gestionarD.repaint();
        gestionarD.revalidate();
        gestionarD.setVisible(true);
    }
     
    Respuestas comprar() {
        int opcion = JOptionPane.showConfirmDialog(null, "¿Quieres comprar la calle actual?","Compra", JOptionPane.YES_NO_OPTION);
        
        if(opcion==0) {
            return Respuestas.SI;
        }
        else{
            return Respuestas.NO;
        }
    }
    
    void mostrarSiguienteOperacion(OperacionesJuego paso){
        String op = paso.toString();
        TextoOperacion.setText(op);
        actualizarVista();
    }
    
    void mostrarEventos() {
        DiarioDialog diarioD = new DiarioDialog(this);
        diarioD.repaint();
        this.revalidate();
    }
     

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Casilla = new javax.swing.JLabel();
        SiguienteOperacion = new javax.swing.JLabel();
        Ranking = new javax.swing.JLabel();
        TextoCasilla = new javax.swing.JTextField();
        TextoOperacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoRanking = new javax.swing.JTextArea();
        contenedorVistaJugador = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("CIVITAS");

        Casilla.setText("Casilla:");

        SiguienteOperacion.setText("Siguiente Operacion:");

        Ranking.setText("Ranking:");

        TextoCasilla.setText("Textocasilla");
        TextoCasilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCasillaActionPerformed(evt);
            }
        });

        TextoOperacion.setText("Textooperacion");
        TextoOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoOperacionActionPerformed(evt);
            }
        });

        TextoRanking.setColumns(20);
        TextoRanking.setRows(5);
        TextoRanking.setText("rankingmostrado\n");
        jScrollPane1.setViewportView(TextoRanking);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Ranking)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(SiguienteOperacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextoOperacion))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Casilla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextoCasilla)))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel1)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Casilla)
                    .addComponent(TextoCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiguienteOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ranking)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoCasillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoCasillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoCasillaActionPerformed

    private void TextoOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoOperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoOperacionActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CivitasView().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Casilla;
    private javax.swing.JLabel Ranking;
    private javax.swing.JLabel SiguienteOperacion;
    private javax.swing.JTextField TextoCasilla;
    private javax.swing.JTextField TextoOperacion;
    private javax.swing.JTextArea TextoRanking;
    private javax.swing.JPanel contenedorVistaJugador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
