/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.TituloPropiedad;

/**
 *
 * @author Usuario
 */
public class PropiedadPanel extends javax.swing.JPanel {

    TituloPropiedad titulo;
    
    void setPropiedad(TituloPropiedad tit) {
        titulo = tit;
        textoNombre.setText(titulo.getNombre());
        String nc = Integer.toString(titulo.getNumCasas());        
        textoCasas.setText(nc);  
        String nh = Integer.toString(titulo.getNumHoteles());      
        textoHoteles.setText(nh);
        String h = Boolean.toString(titulo.getHipotecado());
        textoHipotecada.setText(h);
        
        repaint();
    }
    
    /**
     * Creates new form PropiedadPanel
     */
    public PropiedadPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        propiedades = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textoCasas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textoHoteles = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textoHipotecada = new javax.swing.JTextField();

        jLabel1.setText("Nombre:");
        propiedades.add(jLabel1);

        textoNombre.setEditable(false);
        textoNombre.setText("jTextField1");
        propiedades.add(textoNombre);

        jLabel2.setText("Num. Casas:");
        propiedades.add(jLabel2);

        textoCasas.setEditable(false);
        textoCasas.setText("jTextField1");
        propiedades.add(textoCasas);

        jLabel3.setText("Num. Hoteles:");
        propiedades.add(jLabel3);

        textoHoteles.setEditable(false);
        textoHoteles.setText("jTextField1");
        propiedades.add(textoHoteles);

        jLabel4.setText("Hipotecada:");
        propiedades.add(jLabel4);

        textoHipotecada.setEditable(false);
        textoHipotecada.setText("jTextField1");
        textoHipotecada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoHipotecadaActionPerformed(evt);
            }
        });
        propiedades.add(textoHipotecada);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(propiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(propiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textoHipotecadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoHipotecadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoHipotecadaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel propiedades;
    private javax.swing.JTextField textoCasas;
    private javax.swing.JTextField textoHipotecada;
    private javax.swing.JTextField textoHoteles;
    private javax.swing.JTextField textoNombre;
    // End of variables declaration//GEN-END:variables
}
